### PR TITLE
Fix build failure & misc cleanup

### PR DESCRIPTION
**Pull request by rubberduck203**
- Update prometheus_ex version to fix build failure
- Update credo version to fix build failure
- Purge `deps/` directory
- Fix Travis CI badge
- Add Mix config example

### CODE REVIEW

**Comment by rubberduck203** [comment]
I apologize for the PR containing multiple fixes.
I started with just the intention of fixing the compilation issues, but then noticed a few other things that could use a bit of tender, loving care.

**Comment by rubberduck203** [comment]
@deadtrickster I'm following up on old PRs this morning.
Any chance of this one going mainline?
I'm just trying to figure out if we're going to need to maintain our fork long term or if you're willing to consider merging this in.

**Comment by deadtrickster** [comment]
Hi, I apologize for not replying, somehow missed it :-) Thanks for the contribution!

**Comment by rubberduck203** [comment]
No worries! Thanks for merging this in!

**Pull request merged**
